source:      .
destination: ./_site
includes:    ./_includes

permalink:   /:title.html

#base_url: http://vlandham.com
#base_url: /
description: ""

rdiscount:
  extensions: []

exclude: ['Rakefile', 'README.textile', 'config.rb', 'new.rb', 'template.html']
